default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  username: donation_counter
  host: localhost
  password: <%= ENV['DONATION_COUNTER_DATABASE_PASSWORD'] %>
  database: donation_counter_development

test:
  <<: *default
  username: donation_counter
  host: localhost
  password: <%= ENV['DONATION_COUNTER_DATABASE_PASSWORD'] %>
  database: donation_counter_test

production:
  # Heroku uses the DATABASE_URL value
